version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester
      - image: atmoz/sftp:debian
        command: "test_user:Passw0rd!:::upload"
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: 'Setup virtual env'
          command: |
            virtualenv -p python3 /usr/local/share/virtualenvs/tap-sftp
            source /usr/local/share/virtualenvs/tap-sftp/bin/activate
            pip install .[dev]
      # - run:
      #     name: 'pylint'
      #     command: |
      #       source /usr/local/share/virtualenvs/tap-sftp/bin/activate
      #       make test
      - run:
          name: 'Tap Tester'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox tap-tester.env
            source tap-tester.env
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            cd /root/project/
            run-a-test --tap=tap-sftp \
                       --target=target-stitch \
                       --orchestrator=stitch-orchestrator \
                       --token="$DEV_TOKEN" \
                       --client-id=50 \
                       tap_tester.suites.sftp

workflows:
  version: 2
  commit:
    jobs:
      - build
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
